# Super Differentiator
## Qiang Fei, Shucheng Yan, Jordan Turley
### Harvard University COMPSCI 207

### Introduction

Differentiation has been a major topic of calculus for a long time for its wide application in studies of almost all major science deciplines. It's especially often used in studying the behaviours of models and is also essential for solving optimization problems. Multiple ways have been developed to solve differential equations, through deriving an exact fomula or through estimating by numerical methods. Automatic differentiation is one important way that we use to solve differential problems. It utilizes the power of a computer to replace manual work and yield results with desired efficiency. It’s important because sometimes differentiation requires tedious calculations and is also likely to be inaccurate due to complexity of equations, and we want computers to solve these problems automatically for us. Thus, in this project, we will implement an automatic diffrentiator using forward mode to solve differentiation problems for users.

TODO talk about the extension features


### Background

Chain rule and graph structures will be the cornerstone underlying our program to differentiate various functions. The differentiation process of a complex function can be decomposed into calculating the derivatives of a chain of simple functions. The idea of computation graph will guide how the chain of derivatives will be evaluated and combined to reach the final answer.

#### Chain Rule
One important result in calculus that we use in differentiation is the chain rule, where we calculate the derivative of some function `f(x)` with respect to `x` as the product of the derivative of `f` with respect to some other variable that is also a function of `x` and the derivative of that function with respect to `x`. In mathematical formula, it's represented below:
$$\frac{d}{dx}f\left[u(x)\right] = f'\left[u(x)\right] \cdot u'(x)$$
or
$$\frac{dy}{dx} = \frac{dy}{du} \times \frac{du}{dx}$$
where `f`,`y`,`u` are functions of `x`.
Chain rule also works in multidimentional case when we have a vector of variables. Then `f`,`y`,`u` will be vectors and their derivatives will be matrices. This derivaitve is called the Jacobian. The Jacobian for a function of two inputs and two outputs is shown below.

For $f: \mathbb{R}^2 \rightarrow \mathbb{R}^2, J = \begin{bmatrix}
\frac{\partial f_1}{\partial x} & \frac{\partial f_1}{\partial y} \\
\frac{\partial f_2}{\partial x} & \frac{\partial f_2}{\partial y}
\end{bmatrix}
$

We then take the matrix product of the two calculated derivatives to get the final answer, which is again a vector. Chain rule underlies our automatic differentiation package as it allows us to break down equations to small parts of elementary functions for calculating derivative, and we then aggregate the final result using chain rule. A better exlaination of how we aggregate results will be explained under graph structure of calculation, and before that we would introduce what we mean by elemetary functions. 

#### Elementary functions
By elementary functions, we mean the functions that cannot be decomposed as aan appregation of some functions applied one by another. These functions include +, -, x, /, square root, logarithms and trigonometric functions. The functions input that we are going to deal with can be regarded as a combination of one or more such functions.


#### Graph structure of Calculation
Graph structure of calculate presents better visualization of how we use chain rule to break down complex functions to elememtary functions. Here we include a small example of the graph sturcture of a simple function: $f(x,y) = sin(x) + 2y$
![graph_eg.png](attachment:graph_eg.png)
##### This is an image showing the graphical structure of the given equation. The image cannot be loaded on github but can be seen when this file is open locally. 

As we can see, the sample function is broken into nodes, where each node applies one elementary function to the variable and the function is eventrually composed at the end of the process. Through navigating trhough these nodes, we can calculate the value and derivative at each step and record and update these values when moving forward. At the final node, we shall have the desired result. For vector functions, we can just break each vector into a sequence of functions and apply this method to each of them.

#### Automatic differentiation
The introdution above shows one way of doing automatc differentiation, the forward mode, which we will implement in our package. Indeed, automatic differentiation is a collection of comptational methods to numerically evaluate the derivative of a function through breaking down the function to elementary operations.
It is efficient since we evaluate the function value and its derivative in linear time, based on the complexity of the function, since the chain rule and the graph structure works from the inside with the most basic pieces out to the full complexity of the whole function. It is also precise as it evaluate to machine precision at each step of the process.

TODO talk about the extension features

### How to use SuperDifferentiator

The `SuperDifferentiator` package provides an easy way to calculate the derivative of scalar functions of several inputs and one output, and the Jacobian of vector functions of several inputs and several outputs.

#### Install Package

A user can install our package by cloning the GitHub repository and using `setuptools` or `pip`, or by downloading the package from PyPI. (TODO: Add more details of PyPI after we upload it.) Code demonstrations of installation are given below.

`setuptools`
```
$ git clone https://github.com/super-differentiator/cs207-FinalProject.git
$ cd cs207-FinalProject
$ sudo pip install -r requirements.txt
$ sudo python3 setup.py install
```

`pip`
```
$ git clone https://github.com/super-differentiator/cs207-FinalProject.git
$ cd cs207-FinalProject
$ sudo pip install -r requirements.txt
$ sudo pip install .
```

PyPI: TODO ADD

Then, the package will be installed. Note that the package requires Python version $\ge$ 3.6. To test, open another Terminal and open the `python3` shell and type,

```
>>> from superdifferentiator.forward.functions import X
```

If this executes then you have successfully installed the package.

#### Import Package

For scalar functions of several variables, the user must import each type of function they plan to use. An example is given below, if the user plans to use basic functions, sin, and the natural logarithm.

```
>>> from superdifferentiator.forward.functions import X, Sin, Ln
```

The `superdifferentiator.forward.functions` module provides implementations for the following functions:

- `X`
- Natural logarithm (`Ln`)
- Log base $a$ (`Log`)
- Exponential ($e^{\ldots}$) (`Exp`)
- Absolute value (`Abs`)
- `Sin`
- `Cos`
- `Tan`
- Square root (`Sqrt`)
- `Arcsin`
- `Arccos`
- `Arctan`
- `Sinh`
- `Cosh`
- `Tanh`
- `Logistic`

Examples will be given below in how these functions are used in practice.

For vector functions, the user must import the elementary functions the plan to use, but must also import the `Vector` module, as shown below.

```
>>> from superdifferentiator.forward.Vector import Vector
```

Again, examples will be given below how to use the `Vector` class in practice.

#### Use Package

For scalar functions, the user begins by importing the desired functions they will use. The user begins with an `X` object. `X` represents an independent variable in your function. However, the `X` class can be used for multiple different named independent variables, e.g. $x$, $y$, $z$, or $x_1$, $x_2$, etc. By default, the `X` class refers to the variable $x$, but any name of the variable can be passed in.

First, we will show a simple example of the function $f(x) = \text{sin}\left[\text{ln}(x) + 3x^2 + 2x + 7\right]$ for $x = 3$.

```
>>> from superdifferentiator.forward.functions import X, Ln, Sin
>>> x = X(3)
>>> fx = Sin(Ln(x) + (3 * x ** 2) + (2 * x) + 7)
>>> fx.val
[-0.25505810186107586]
>>> fx.der
{'x': [-19.6608231486877]}
```

We see the function value is about -0.255, and the derivative with respect to $x$ is -19.66. We can also evaluate the function for multiple values of $x$, as shown below. We will evaluate the same $f(x)$ for $x = 3$, $x = 5$, and $x = 7$.

```
>>> from superdifferentiator.forward.functions import X, Ln, Sin
>>> x = X([3, 5, 7])
>>> fx = Sin(Ln(x) + (3 * x ** 2) + (2 * x) + 7)
>>> fx.val
[-0.25505810186107586, -0.5958645016385826, 0.295431220759494]
>>> fx.der
{'x': [-19.6608231486877, 25.8593365682129, 42.17249706362]}
```

We see $f(3) = -0.255, f'(3) = -19.66, f(5) = -0.596, f'(5) = 25.859, f(7) = 0.295,$ and $f'(7) = 42.172$. This allows us to simultaneously evaluate the function for several values of $x$ without any extra hassle for the user.

Next, we look at scalar functions of multiple variables. We will consider the function $f(x, y) = 2x^2 + 3y$ for $x = 2, y = 3$.

```
>>> from superdifferentiator.forward.functions import X
>>> x = X(2, 'x')
>>> y = X(3, 'y')
>>> f_xy = (2 * x ** 2) + (3 * y)
>>> f_xy.val
[17]
>>> f_xy.der
{'x': [8], 'y': [3]}
```

We see that $f(2, 3) = 17, \frac{\partial f}{\partial x}(2, 3) = 8,$ and $\frac{\partial f}{\partial y}(2, 3) = 3$. Again, the function can be evaluated for multiple values of $x$ and $y$. However, the length of the lists passed to the different `X` objects must be the same.

For vector functions, the user must also import the `Vector` class. We will consider the function $f(x, y) = \begin{bmatrix}
2x + 3y \\
Sin(x + y)
\end{bmatrix}$ for $x = 3, y = 5$.

```
>>> from superdifferentiator.forward.functions import X, Sin
>>> from superdifferentiator.forward.Vector import Vector
>>> x = X(3, 'x')
>>> y = X(5, 'y')
>>> f1 = (2 * x) + (3 * y)
>>> f2 = Sin(x + y)
>>> v = Vector([f1, f2])
>>> v.val[0]
array([[21.        ],
       [ 0.98935825]])
>>> variables, jacs = v.jacobian()
>>> variables
['x', 'y']
>>> jacs[0]
array([[ 2.        ,  3.        ],
       [-0.14550003, -0.14550003]])
```

This code is a bit more confusing, so we will step through it line by line. We begin by creating the $x$ and $y$ objects from the `X` class. Then, we create each function of the vector function, and create a `Vector` object, passing the list of functions. We get the function value by referencing `v.val`, which returns a list of column vectors for the function value. Each element in the list refers to the list of inputs given by the `X` objects. Since we only passed one input, the output of `v.val` was a list of length 1. We reference the Jacobian by calling `v.jacobian()`, which returns the list of variables in the order they are in the Jacobian, and the list of Jacobian matrices evaluated at the inputs. We return the variables because there is no way to know what order the partial derivatives are in the matrix alone. Again, since we only passed one input to the `X` objects, the `jacs` list is length 1. If we passed multiple variables to the `X` object, then we would get multiple column vectors in `v.val` and multiple matrices in `jacs`.

Below, we give an example of the function $f(x, y) = \begin{bmatrix}
2x^2 + 3y^4 \\
x + 4y^2
\end{bmatrix}$ for $x = 3, y = 5$ and $x = 1, y = 2$.

```
>>> x = X([3, 1], 'x')
>>> y = X([5, 2], 'y')
>>> f1 = (2 * x ** 2) + (3 * y ** 4)
>>> f2 = x + (4 * y ** 2)
>>> v = Vector([f1, f2])
>>> v.val[0] # Function value for x = 3, y = 5
array([[1893.],
       [ 103.]])
>>> v.val[1] # Function value for x = 1, y = 2
array([[50.],
       [17.]])
>>> variables, jacs = v.jacobian()
>>> variables
['y', 'x']
>>> jacs[0] # Jacobian for x = 3, y = 5
array([[1.5e+03, 1.2e+01],
       [4.0e+01, 1.0e+00]])
>>> jacs[1] # Jacobian for x = 1, y = 2
array([[96.,  4.],
       [16.,  1.]])
```

### Software Organization

Discuss how you plan on organizing your software package.

* What will the directory structure look like?

```
driver.py
superdifferentiator\
    __init__.py
    forward\
        __init__.py
        AD.py
        Vector.py
        functions.py
    tests\
        __init__.py
        test_AD.py
        test_Vector.py
        test_invalid.py
```

* What modules do you plan on including? What is their basic functionality?

We have three modules, `AD.py`, `Vector.py`, and `functions.py`. The `AD.py` module contains the `AD` class. We talk more about the specific implementation below, but the `AD` class stores the function value and derivative for a function, and implements all of the operator overloading, so that we can easily add, subtract, multiply, etc. functions with each other. This is the base class that all of the elementary function classes extend from.

The `Vector.py` module contains the `Vector` class. This class stores a list of `AD` objects for use as a vector function of several inputs and several outputs. This class allows the user to get the value of the vector function in the form of a column vector, as well as calculate the Jacobian matrix.

The `functions.py` class contains several classes for each elementary function, `X`, `Ln`, `Log`, `Exp`, `Abs`, `Sin`, `Cos`, `Tan`, `Sqrt`, `Arcsin`, `Arccos`, `Arctan`, `Sinh`, `Cosh`, `Tanh`, and `Logistic`. Since each of these extend from AD, they have their function value and derivative stored, and are also able to interact with each other through operator overloading. These classes and their implementation is discussed more below.

* Tests
    - All tests are saved in files test_AD.py, test_Vector.py, and test_invalid.py under /code/tests directory.
    - We run them with help of TravisCI and CodeCov, where TravisCI will automatically check if all tests are passed when we pushed codes written in local repository to github, and CodeCov will automatically check the test coverage.
    - We have badges put in the README file for both TravisCI and CodeCov, which will tell if the result for the most recent pull. We only merge new changes to master branch when test results are positive.

* How can someone install your package?

The detailed instruction is included in the section `How to Use SuperDifferentiator`. The user can clone from GitHub and use setuptools or pip, or can install from PyPI.

### Implementation

* What are the core data structures?

For a scalar function of a single variable or many variables, we use two core data structures: lists and dictionaries, as well as a string to represent the name of the variable, like 'x', 'y', 'x_1', 'var1', or whatever the user desires. Since the user is able to evaluate the function for many inputs, we store the function output in a list, where the index corresponds to the index of the value given as input, which are also given as lists. We store the partial derivatives of a function as a dictionary, where the key corresponds to the name of the variable, which is either 'x' by default or given by the user, and the value is a list of floats, each corresponding to the partial derivative of the function with respect to the variable for the given input. A demonstration of this is given above in the How to use SuperDifferentiator $\rightarrow$ Use Package section.

For a vector function of many inputs and many outputs, we store each function in the vector as an `AD` object. As a result, it gets all of the same data structures used as above, which make it easy to get the function value and partial derivatives. The function value is given as a list of column vectors (using numpy), where each column vector in the list corresponds to the given input at that index. If the user just needs to evaluate the function for one value, then the list will be length one. The Jacobian function returns the list of variables in the order they appear in the Jacobian matrix, as well as a list of matrices (using numpy) which are the Jacobian evaluated at each of the given inputs. Since there is no implicit ordering of the variables given, as the user can give the variable names, we return the list of variables in the order that they appear in the Jacobian, to make it easy for the user to see which column corresponds to which variable. Again, if the user just needs to evaluate the Jacobian at one value, then this list will be length one. Again, demonstrations of this are given in the How to use SuperDifferentiator $\rightarrow$ Use Package section.

* What classes will you implement?

The base class for all functionality is the `AD` class, located in the `AD.py` module. This class stores the function values and the partial derivatives at the points the user wants to evaluate. In this class we also implement all of the operator overloading by implementing the `__add__`, `__mul__`, `__sub__`, etc. methods. This allows us to easily interact AD objects to build the function we want the derivative of.

We also have classes for each elementary operation in the `functions.py` module: `X`, `Ln`, `Log`, `Exp`, etc. These all extend from the `AD` class so they can be interacted using python's build in operations. We decided to make these classes instead of functions that could return an AD object since it made more sense that these functions themselves would be AD objects, which have a function value and derivative. However, we could have implemented functions instead for these and the result would have been almost identical for the user. On the user's side, the difference would not be seen.

The `X` class is where the user starts, passing in the value or values of $\alpha$ that they want to evaluate the function value and derivative at, in the form of a single value or a list of values. From this, the user can build more complex functions, like polynomials using python operations +, -, \*, /, and \*\*, or can build functions involving the elementary function. When you instantiate an object of one of the elementary functions, you pass in the function that you want this elementary function to take the value of (the `Log` class also takes the base of the log as the second argument). For example, if you build the function $f(x) = x^2 + 2x + 3$ and want to find the sin of this function at $\alpha = 2$, you can do so as demonstrated below.

```
>>> x = X(2)
>>> fx = (x ** 2) + (2 * x) + 3
>>> sin_fx = Sin(fx)
```

* What method and name attributes will your classes have?

We have three attributes, which are `vals`, `der`, `s`, and `repr_s`, which are stored in the `AD` class. The `vals` and `der` attributes store the function value and partial derivatives, and the `s` and `repr_s` attributes store string representations of the function, which will be shown below.

```
>>> from superdifferentiator.forward.functions import X, Sin
>>> x = X(3, 'x')
>>> y = X(4, 'y')
>>> f_xy = Sin((x ** 2) + (y ** 3))
>>> str(f_xy) # returns the s attribute
"Sin(((X(x, 'x')) ** (2)) + ((X(y, 'y')) ** (3)))"
```

This string representation has two purposes. First, it shows what the function is that is being evaluated. Second, it allows the user to use this string representation with other values of their inputs farly easily, rather than parsing through the function trying to replace the values with other values. This is shown below.

```
>>> s = str(f_xy)
>>> x = 5
>>> y = 8
>>> new_f_xy = eval(s)
>>> new_f_xy.val
[0.21075159869536875]
>>> new_f_xy.der
{'x': [-9.775396481203952], 'y': [-187.6876124391159]}
```

This gives us the function value and partial derivatives at $x = 5, y = 8$, whereas before we could only evaluate for $x = 3, y = 4$! This gives the user one potential way to evaluate the same function for other values of $x$ and $y$ without a lot of trouble. Of course, the user could just remake `f_xy`, but if the user is passing an `AD` object to a function, and then the function needs to evaluate the `AD` object for different inputs without getting a new `AD` object from the user, this is one potential way to do it.

We also store the original instantiation of the function, which can be retrieved using the `repr` function, as shown below. This allows for exact reproducibility of the function you are evaluating.

```
>>> x = X(3)
>>> fx = (x ** 2) + (2 * x) + 3
>>> fx.val
[18]
>>> fx.der
{'x': [8]}
>>> repr(fx)
"(((X([3], 'x')) ** (2)) + ((X([3], 'x')) * (2))) + (3)"
>>> fx2 = eval(repr(fx))
>>> fx2.val
[18]
>>> fx2.der
{'x': [8]}
```

In the `AD` class we implement the following functions for operator overloading: `__add__`, `__radd__`, `__mul__`, `__rmul__`, `__sub__`, `__rsub__`, `__neg__`, `__truediv__`, `__rtruediv__`, `__pow__`, and `__rpow__`. This allows the user to make full use of the python operators +, -, \*, /, and \*\*. Since each elementary function class extends from `AD`, they get the full functionality as well.

The `Vector` is relatively simple in that it only stores a list of `AD` objects. To get the function value or Jacobian, we just loop over these `AD` objects and pull the function value and/or the partial derivatives, and return the from the `Vector` class in the form of a column vector or a matrix.

Finally, the elementary function classes, like `Ln`, `Sin`, etc. do not themselves store anything extra, but since they extend from `AD`, they get the same attributes listed above.

### Extension